import type { PlaybookWorkflowContent } from '@/lib/playbookWorkflow';
import { playbookContent, workflow } from '../helpers';

function docsPlaybook(name: string, tool: string): PlaybookWorkflowContent {
  return playbookContent(
    `${name} playbooks`,
    'on the board.',
    `${name} workflows traced with GitHub, Notion, and approval gates.`,
    [
      workflow(
        'generate',
        'Generate docs',
        'Source updated',
        [
          { label: 'Repo change', kind: 'trigger', iconDomain: 'github.com' },
          { label: `Draft ${name.toLowerCase()}`, kind: 'agent', agent: 'Claude Code' },
          { label: 'Review structure', kind: 'agent', agent: 'Codex' },
          { label: `Save to ${tool}`, kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Editor gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'First-pass quality', value: '86% accepted' },
      ),
      workflow(
        'refresh',
        'Refresh stale docs',
        'Cron weekly',
        [
          { label: 'Stale scan', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Diff vs code', kind: 'agent', agent: 'Codex' },
          { label: 'Propose updates', kind: 'agent', agent: 'OpenCode' },
          { label: 'Open PR', kind: 'integration', iconDomain: 'github.com' },
          { label: 'Merge gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Stale pages fixed', value: '14 avg per run' },
      ),
      workflow(
        'publish',
        'Publish flow',
        'Review approved',
        [
          { label: 'Approved draft', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Final polish', kind: 'agent', agent: 'Claude Code' },
          { label: 'Link artifacts', kind: 'agent', agent: 'Codex' },
          { label: 'Notify #docs', kind: 'integration', iconDomain: 'slack.com' },
          { label: 'Publish gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Publish latency', value: '2 days → 3 hours' },
      ),
    ],
  );
}

export const LEGACY_FEATURE_PLAYBOOKS: Record<string, PlaybookWorkflowContent> = {
  'ai-documentation-agent': docsPlaybook('Documentation', 'Notion'),
  'code-to-docs': docsPlaybook('Code to docs', 'Notion'),
  'automated-screenshots-for-docs': playbookContent(
    'Screenshot playbooks',
    'for docs.',
    'Capture UI, annotate, and attach to documentation — traced on the board.',
    [
      workflow(
        'capture',
        'UI capture',
        'Docs mission',
        [
          { label: 'Page URL', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Browser capture', kind: 'agent', agent: 'Claude Code' },
          { label: 'Annotate regions', kind: 'agent', agent: 'Codex' },
          { label: 'Attach to doc', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Review gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Capture accuracy', value: '98% pixel match' },
      ),
      workflow(
        'batch',
        'Batch screenshots',
        'Release cut',
        [
          { label: 'Release ticket', kind: 'trigger', iconDomain: 'github.com' },
          { label: 'Route all views', kind: 'agent', agent: 'OpenCode' },
          { label: 'Batch capture', kind: 'agent', agent: 'Codex' },
          { label: 'Upload assets', kind: 'integration', iconDomain: 'google.com' },
          { label: 'QA gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Views captured', value: '24 avg per release' },
      ),
      workflow(
        'changelog',
        'Changelog visuals',
        'Feature shipped',
        [
          { label: 'Feature live', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Before/after', kind: 'agent', agent: 'Claude Code' },
          { label: 'Caption draft', kind: 'agent', agent: 'OpenCode' },
          { label: 'Post changelog', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Publish gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Changelog coverage', value: '100% visual diffs' },
      ),
    ],
  ),
  'chrome-extension-for-documentation': playbookContent(
    'Extension playbooks',
    'in the browser.',
    'Document workflows from Chrome — capture steps, screenshots, and publish to your wiki.',
    [
      workflow(
        'record',
        'Record workflow',
        'Extension click',
        [
          { label: 'Start recording', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Trace clicks', kind: 'agent', agent: 'Claude Code' },
          { label: 'Draft steps', kind: 'agent', agent: 'Codex' },
          { label: 'Save draft', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Author gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Step accuracy', value: '94% verified' },
      ),
      workflow(
        'annotate',
        'Annotate page',
        'Page captured',
        [
          { label: 'Active tab', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Highlight UI', kind: 'agent', agent: 'OpenCode' },
          { label: 'Write caption', kind: 'agent', agent: 'Claude Code' },
          { label: 'Sync wiki', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Publish gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Time to publish', value: '45 min → 8 min' },
      ),
      workflow(
        'sync',
        'Wiki sync',
        'Cron daily',
        [
          { label: 'Daily sync', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Detect drift', kind: 'agent', agent: 'Codex' },
          { label: 'Propose fixes', kind: 'agent', agent: 'Claude Code' },
          { label: 'Notify #docs', kind: 'integration', iconDomain: 'slack.com' },
          { label: 'Merge gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Drift caught', value: '< 24 hr lag' },
      ),
    ],
  ),
  'ai-help-center': playbookContent(
    'Help center playbooks',
    'that deflect.',
    'Answer articles, route tickets, and escalate — traced with KB and Slack.',
    [
      workflow(
        'deflect',
        'Self-service deflect',
        'Widget query',
        [
          { label: 'User question', kind: 'trigger', iconDomain: 'gator' },
          { label: 'KB search', kind: 'agent', agent: 'Codex' },
          { label: 'Draft answer', kind: 'agent', agent: 'Claude Code' },
          { label: 'Return article', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Quality gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Deflection rate', value: '+38% on new articles' },
      ),
      workflow(
        'route',
        'Ticket routing',
        'No KB match',
        [
          { label: 'Escalation', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Classify intent', kind: 'agent', agent: 'OpenCode' },
          { label: 'Create ticket', kind: 'agent', agent: 'Claude Code' },
          { label: 'Assign queue', kind: 'integration', iconDomain: 'zendesk.com' },
          { label: 'Triage gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Routing accuracy', value: '91%' },
      ),
      workflow(
        'refresh-kb',
        'KB refresh',
        'Cron weekly',
        [
          { label: 'Gap analysis', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Top unanswered', kind: 'agent', agent: 'Codex' },
          { label: 'Draft articles', kind: 'agent', agent: 'Claude Code' },
          { label: 'Editor review', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Publish gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'New articles', value: '6 avg per week' },
      ),
    ],
  ),
  'generative-ai-customer-service': playbookContent(
    'Support playbooks',
    'with escalation.',
    'Triage tickets, draft replies, and escalate — traced with Zendesk and Slack.',
    [
      workflow(
        'triage',
        'Ticket triage',
        'New ticket',
        [
          { label: 'Ticket opened', kind: 'trigger', iconDomain: 'zendesk.com' },
          { label: 'Classify intent', kind: 'agent', agent: 'Codex' },
          { label: 'KB lookup', kind: 'agent', agent: 'Claude Code' },
          { label: 'Assign queue', kind: 'integration', iconDomain: 'zendesk.com' },
          { label: 'Priority gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'First response', value: '2 hr → 12 min' },
      ),
      workflow(
        'reply',
        'Draft reply',
        'Agent assigned',
        [
          { label: 'Reply needed', kind: 'trigger', iconDomain: 'intercom.com' },
          { label: 'Thread context', kind: 'agent', agent: 'OpenCode' },
          { label: 'Draft response', kind: 'agent', agent: 'Claude Code' },
          { label: 'Hold for review', kind: 'integration', iconDomain: 'gmail.com' },
          { label: 'Send gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Draft acceptance', value: '84% sent as-is' },
      ),
      workflow(
        'escalate',
        'Escalation',
        'SLA risk',
        [
          { label: 'SLA warning', kind: 'trigger', iconDomain: 'zendesk.com' },
          { label: 'Summarize case', kind: 'agent', agent: 'Codex' },
          { label: 'Escalation note', kind: 'agent', agent: 'Claude Code' },
          { label: 'Alert #support', kind: 'integration', iconDomain: 'slack.com' },
          { label: 'Manager gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'SLA breaches', value: 'Down 52%' },
      ),
    ],
  ),
  'internal-knowledge-base': playbookContent(
    'Wiki playbooks',
    'agents maintain.',
    'Load context, update pages, and cross-link — traced on every mission.',
    [
      workflow(
        'load',
        'Context load',
        'Mission start',
        [
          { label: 'Ticket opened', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Search wiki', kind: 'agent', agent: 'Codex' },
          { label: 'Inject context', kind: 'agent', agent: 'Claude Code' },
          { label: 'Attach refs', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Scope gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Relevant hits', value: '93% precision' },
      ),
      workflow(
        'update',
        'Page update',
        'Decision logged',
        [
          { label: 'Outcome noted', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Draft update', kind: 'agent', agent: 'Claude Code' },
          { label: 'Cross-link', kind: 'agent', agent: 'OpenCode' },
          { label: 'Save wiki', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Editor gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Wiki freshness', value: '< 48 hr lag' },
      ),
      workflow(
        'audit',
        'Wiki audit',
        'Cron monthly',
        [
          { label: 'Monthly audit', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Find stale pages', kind: 'agent', agent: 'Codex' },
          { label: 'Propose fixes', kind: 'agent', agent: 'Claude Code' },
          { label: 'Notify owners', kind: 'integration', iconDomain: 'slack.com' },
          { label: 'Cleanup gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Stale pages fixed', value: '22 avg per audit' },
      ),
    ],
  ),
  'multilingual-knowledge-base': playbookContent(
    'Multilingual playbooks',
    'one source.',
    'Translate articles, localize replies, and sync locales — traced with approval gates.',
    [
      workflow(
        'translate',
        'Article translate',
        'New locale',
        [
          { label: 'Source article', kind: 'trigger', iconDomain: 'notion.so' },
          { label: 'Translate draft', kind: 'agent', agent: 'Claude Code' },
          { label: 'Locale QA', kind: 'agent', agent: 'Codex' },
          { label: 'Publish locale', kind: 'integration', iconDomain: 'notion.so' },
          { label: 'Native gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Translation quality', value: '4.6/5 reviewer score' },
      ),
      workflow(
        'reply-locale',
        'Localized reply',
        'Ticket in locale',
        [
          { label: 'Non-EN ticket', kind: 'trigger', iconDomain: 'zendesk.com' },
          { label: 'Detect language', kind: 'agent', agent: 'OpenCode' },
          { label: 'Draft reply', kind: 'agent', agent: 'Claude Code' },
          { label: 'Send response', kind: 'integration', iconDomain: 'gmail.com' },
          { label: 'Send gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'CSAT in locale', value: '+15% vs EN-only' },
      ),
      workflow(
        'sync-locales',
        'Locale sync',
        'Source updated',
        [
          { label: 'EN page changed', kind: 'trigger', iconDomain: 'notion.so' },
          { label: 'Flag drift', kind: 'agent', agent: 'Codex' },
          { label: 'Update locales', kind: 'agent', agent: 'Claude Code' },
          { label: 'Notify #i18n', kind: 'integration', iconDomain: 'slack.com' },
          { label: 'Publish gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Locale drift', value: '< 72 hr sync' },
      ),
    ],
  ),
  'self-service-help-widget': playbookContent(
    'Widget playbooks',
    'embedded help.',
    'Answer in-widget, capture leads, and escalate — traced on the board.',
    [
      workflow(
        'widget-answer',
        'In-widget answer',
        'User query',
        [
          { label: 'Widget open', kind: 'trigger', iconDomain: 'gator' },
          { label: 'KB search', kind: 'agent', agent: 'Codex' },
          { label: 'Compose answer', kind: 'agent', agent: 'Claude Code' },
          { label: 'Return in widget', kind: 'integration', iconDomain: 'gator' },
          { label: 'Quality gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Resolution rate', value: '67% without ticket' },
      ),
      workflow(
        'lead-capture',
        'Lead capture',
        'High intent',
        [
          { label: 'Pricing question', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Qualify lead', kind: 'agent', agent: 'OpenCode' },
          { label: 'Draft follow-up', kind: 'agent', agent: 'Claude Code' },
          { label: 'Log to CRM', kind: 'integration', iconDomain: 'hubspot.com' },
          { label: 'Sales gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Lead conversion', value: '+24% vs form-only' },
      ),
      workflow(
        'widget-escalate',
        'Escalate to human',
        'Low confidence',
        [
          { label: 'Confidence low', kind: 'trigger', iconDomain: 'gator' },
          { label: 'Summarize chat', kind: 'agent', agent: 'Codex' },
          { label: 'Create ticket', kind: 'agent', agent: 'Claude Code' },
          { label: 'Hand to agent', kind: 'integration', iconDomain: 'zendesk.com' },
          { label: 'Assign gate', kind: 'gate', iconDomain: 'gator' },
        ],
        { label: 'Handoff satisfaction', value: '4.4/5 avg' },
      ),
    ],
  ),
};
